# Config for streaming proxy

livekit:
  uri: https://meet.paxintrade.com/livekit
  api_key: APIiYAA5w37Cfo2
  api_secret: 6aNur7qqupeZhFYNOJVUyeXxXhVw8f4lm13pEDUx8SgB

auth:
  uri: https://go.paxintrade.com/api/auth/check

backend:
  uri: https://go.paxintrade.com/api

redis:
  url: localhost:6379
