# Config for streaming proxy

auth_uri: https://go.paxintrade.com

whitelists: [https://meet.paxintrade.com/livekit]

livekit:
  api_key: APIiYAA5w37Cfo2
  api_secret: 6aNur7qqupeZhFYNOJVUyeXxXhVw8f4lm13pEDUx8SgB
