FROM golang:1.22-alpine as builder

WORKDIR /app

COPY . .
RUN go mod download
RUN go mod tidy
RUN go build -o bin/paxintrade-streaming cmd/server/main.go


FROM keymetrics/pm2:18-alpine

WORKDIR /app

COPY --from=builder  /app/bin/paxintrade-streaming .
RUN chmod ++x /app/paxintrade-streaming

CMD ["pm2-runtime", "paxintrade-streaming"]